### PR TITLE
More Events

### PR DESCRIPTION
**Pull request by edobry**
This PR adds a few new features to `MXDev`, mostly around reporting on more event types.

#### Changes:
- implemented Babel transpilation, can now use modern ES2016 on Lambda
   - for this, moved all existing code into the new `src` dir, which is why the diffs are large
- upgraded the Github integration from an OAuth application to a full-fledged Github App
- refactored some code to use `async`/`await`
- new events:
   - PR rejection
   - failed test
   - PR `ready` label
      - JIRA issues autotransition
   - PR open/edit
      - JIRA issue `Fix Version` is updated based on target release branch
- fixed a bug where editing an approval message would cause it to fire

### CODE REVIEW

**Review by fcamilleri22 — APPROVED** [review]
YUS!

I think I got used to reading destructured args, too.

**Comment by fcamilleri22** [comment]
An addition: if there is a test: fail, JIRA needs to update. If its in the ready column, the issue needs to move back, and if it has any testers, the tester list needs to be cleared. @edobry

**Comment by fcamilleri22** [comment]
Bug: If you edit a comment that includes [Test: Pass] or [Test: Fail], the fail or pass alert will refire. Should probably be a new event type or just fire off the "$X commented on $Y" alert

**Comment by edobry** [comment]
@fcamilleri22 both comments addressed, functionality implemented and tested. free free to retest if u want, and then acknowledge and i'll merge.

**Review by fcamilleri22 — APPROVED** [review]
YES.

Very nice.

**Pull request merged**
